#!/bin/bash
# get a shell in the latest started local container

latestcontainer=$( nerdctl ps -q -n1 )
if test ! -z "$1" ; then
  echo searching SHELLs on "$1"
  nerdctl exec "$1" ls /bin/ash &>/dev/null && nerdctl exec -it -u root "$1" ash
  nerdctl exec "$1" ls /bin/bash &>/dev/null && nerdctl exec -it -u root "$1" bash
elif nerdctl ps | grep "$latestcontainer" >/dev/null ; then
  echo searching SHELLs on "$latestcontainer"
  nerdctl exec "$latestcontainer" ls /bin/ash &>/dev/null && nerdctl exec -it -u root "$latestcontainer" ash
  nerdctl exec "$latestcontainer" ls /bin/bash &>/dev/null && nerdctl exec -it -u root "$latestcontainer" bash
  echo
else
  echo ERROR: no running containers >&2
  exit
fi
