#!/bin/bash
# kill latest or specified nerdctl container

if test ! -z "$1" ; then
  nerdctl rm -f "$1"
  else
  latestcontainer=$( nerdctl ps -n1 -q )
  if test ! -z "$latestcontainer" ; then
    nerdctl rm -f "$latestcontainer"
  else
    echo No running containers >&2
    exit
  fi
fi
