#!/bin/bash
# macos: update os, applications, homebrew etc

if [[ $(uname -s) != "Darwin" ]]; then
  echo "script for macOS"
  exit 1
fi

if [[ -x "$(command -v tldr)" ]]; then
  tldr --update
fi

if [[ -x "$(command -v brew)" ]]; then
  brew update
  brew upgrade
  brew cleanup
  brew doctor
fi

softwareupdate -i -a
