#!/bin/bash
# edit source code of any script in this directory. use any var2 to prevent auto git pull/push

set -e
sourcedir=${PWD}
targetpath=$( which "$1" )
cd "$(dirname "$0")"
echo "checking for remote changes..."
test ! -z "$2" || git pull --ff-only
if [[ -z "$1" ]] ; then
	echo "exiting."
	exit 0
fi
nano "${targetpath}"
chmod +x "${targetpath}"
changes=$( git status 2>&1 )
