#!/bin/bash
# Set the prompt '$PS1' variable

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1) /'
}
export PS1=" \[\e[35m\]\u\[\e[36m\]@\[\e[37m\]\h \[\e[33m\]\w \[\e[32m\]\$(parse_git_branch)\[\e[1;30m\]"'\$'"\[\e[0m\] "
